### ISSUE TITLE
Music files missing in this commit.

### ISSUE THREAD

**Issue by RSC-Games** [MacroPixel/untitled-platformer#1]
When I went to play your game, the traceback reported that the music files were missing. I investigated, and no music folder was present in res/sounds, and the files were not in the sounds directory either.

SYSTEM INFO:
OS: Windows 10
CPU: Intel Core i3-8145u
RAM: 4 GB DDR4 2400 MHz

**Comment by MacroPixel** [comment]
I apparently added the music folder to .gitignore (no clue why), so it's fixed now. Thanks for letting me know!
